language: node_js
cache:
  directories:
    - ~!@/.npm

node_js:
  - '9'

git:
  depth: 3
script:
  - yarn build
  - echo 'lariicsa.com' > public/CNAME

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GIT_TOKEN
  local-dir: dist/
  target-branch: master
  commit_message: "Lara Deploy release ${TRAVIS_TAG}"
  on:
    branch: develop